services:
  haproxy:
    image: haproxy:3.1-alpine
    ports:
      - 9999:9999
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30M"

  api1: &api
    image: ${API_IMAGE:-vigilant:latest}
    build: .
    environment:
      INDEX_PATH: /data/index.bin
      MCC_RISK_PATH: /data/mcc_risk.json
    volumes:
      - ./data:/data:ro
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150M"

  api2:
    <<: *api
