services:
  haproxy:
    image: haproxy:3.1-alpine
    ports:
      - 9999:9999
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50M"

  api1: &api
    image: ${API_IMAGE:-vigilant:latest}
    build: .
    environment:
      QUARKUS_HTTP_DOMAIN_SOCKET: /sockets/api1.sock
      QUARKUS_HTTP_DOMAIN_SOCKET_ENABLED: "true"
      INDEX_PATH: /app/data/index.bin
      MCC_RISK_PATH: /app/data/mcc_risk.json
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150M"

  api2:
    <<: *api
    environment:
      QUARKUS_HTTP_DOMAIN_SOCKET: /sockets/api2.sock
      QUARKUS_HTTP_DOMAIN_SOCKET_ENABLED: "true"
      INDEX_PATH: /app/data/index.bin
      MCC_RISK_PATH: /app/data/mcc_risk.json

volumes:
  sockets:
