quarkus.http.port=-1
quarkus.vertx.event-loops-pool-size=4
quarkus.vertx.worker-pool-size=16
quarkus.log.level=WARN
quarkus.native.additional-build-args=-march=haswell,--gc=serial,-H:+PrintExceptionInformation
